export const LOADARTICLES = 'LOADARTICLES';
export const LOADARTICLES_SUCCESS = 'LOADARTICLES_SUCCESS';
export const LOADARTICLES_FAILURE  = 'LOADARTICLES_FAILURE ';
export const LOADCOUNTARTICLES  = 'LOADCOUNTARTICLES ';
export const LOADCOUNTARTICLES_SUCCESS  = 'LOADCOUNTARTICLES_SUCCESS ';
export const LOADCOUNTARTICLES_FAILURE  = 'LOADCOUNTARTICLES_FAILURE ';

export const LOADPAGINATEDDATAS  = 'LOADPAGINATEDDATAS ';
export const LOADPAGINATEDDATAS__SUCCESS  = 'LOADPAGINATEDDATAS__SUCCESS ';
export const LOADPAGINATEDDATAS_FAILURE  = 'LOADPAGINATEDDATAS_FAILURE ';



export const COLLABARATORSDDATAS  = 'COLLABARATORSDDATAS ';
export const COLLABARATORSDDATAS__SUCCESS  = 'COLLABARATORSDDATAS__SUCCESS ';
export const COLLABARATORSDDATAS_FAILURE  = 'COLLABARATORSDDATAS_FAILURE ';